### ISSUE TITLE
serializeNode function need to hack Google Chrome

### ISSUE THREAD

**Issue by Gorden-Wang** [rrweb-io/rrweb-snapshot#14]
First of all , It's a great work ~ thanks man.
When i try to replay user behavior, I found an error。

https://github.com/rrweb-io/rrweb-snapshot/blob/0865c829488cf8caa444e6221ab4e84040fc74a1/src/snapshot.ts#L161

![image](https://user-images.githubusercontent.com/6468548/60639031-578f6400-9e53-11e9-8766-f72ead0313aa.png)

It might be 
```
!(
   (n as HTMLElement).innerText || (n as HTMLElement).textContent
).trim().length 
```

**Comment by Yuyz0112** [comment]
@Gorden-Wang Thanks for the report
