### ISSUE TITLE
可以支持 canvas 的内容记录吗

### ISSUE THREAD

**Issue by wuzekang** [rrweb-io/rrweb-snapshot#19]
目前 canvas 的内容不支持记录, 能否使用 canvas 的相关api 保存当前的内容

**Comment by wuzekang** [comment]
这边用 canvas.toDataURL 实现了一个可以 snapshot -> rebuild 的版本, 感觉用来截图还行, 如果用来 record replay 可能最终录制的 JSON 偏大, 我提个PR给你看看哈

**Comment by Yuyz0112** [comment]
👌。大没关系，可以作为配置项可选是否开启
