### ISSUE TITLE
请问这个如何使用，能否出一个使用文档和示例？

### ISSUE THREAD

**Issue by weiweiok** [rrweb-io/rrweb-snapshot#37]
我原本在用 rrweb 来录制页面，但发现他不支持 canvas 。
于是我找到了这个，似乎这个是支持 canvas 的，但我不知道该如何使用。
下载源码在本地编译后，没有看到例子

**Comment by Yuyz0112** [comment]
这个对 canvas 也是静态的支持，观测不了变化，rrweb 内部使用了 rrweb-snapshot 做全量快照。

对于 canvas 的需求可以做一个最小的 repo 给我用于测试吗？这样会加快功能的开发。

**Comment by xukaisjz** [comment]
能否支持生成视频格式文件，如：mp4、avi等等

**Comment by Yuyz0112** [comment]
canvas 请参考 https://github.com/rrweb-io/rrweb/pull/296#issuecomment-678614581

转换为视频请参考 https://github.com/rrweb-io/rrweb/issues/40#issuecomment-674940396
