### ISSUE TITLE
Failed to execute 'createDocumentType' on 'DOMImplementation': The qualified name provided is empty.

### ISSUE THREAD

**Issue by sumbatx15** [rrweb-io/rrweb-snapshot#42]
Hi there awesome people,  
If the DOCTYPE has no name in it (HTML or whatever) like so
![image](https://user-images.githubusercontent.com/28981577/91330183-c35c2b00-e7d1-11ea-8e19-3e3845e7d456.png)

Then the node will look like this after the recorder 
  `    {
            type: 1,
            name: '',
            publicId: '',
            systemId: '',
            id: 2
          },`

And then when we try to replay that it tries to createDocumentType with no name
![image](https://user-images.githubusercontent.com/28981577/91330543-4087a000-e7d2-11ea-8232-bf74e6553d25.png)

and fails with this message
**Uncaught DOMException: Failed to execute 'createDocumentType' on 'DOMImplementation': The qualified name provided is empty.**

I would suggest to make a default value of HTML 
`n.name || 'html'`

Like your job, keep up the good work !

**Comment by Yuyz0112** [comment]
Thanks for the report and suggestions!
