### ISSUE TITLE
How to rebuild the collected events from record function ?

### ISSUE THREAD

**Issue by muaazrafi** [rrweb-io/rrweb-snapshot#62]
So not understanding how to rebuild the DOM and place it inside iframe to further overlay heatmap on it, I did try to give the early events to the function but I might be not correct there. Any help will be appreciated, currently writing JSON file directly to S3 from which needs to generate a copy of the DOM.

**Comment by Yuyz0112** [comment]
@muaazrafi You can check this code: https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L537

**Comment by muaazrafi** [comment]
Thank you for building such awesome tool and making it opensource, will look into the above line code. So basically for heatmap and clickmap will need to rebuild the snapshot with certain resolution 1248 x 1024 to render it. Than convert click events percentage to map the heat-points and draw the map over it. This is the general approach going with but if you have another suggestion will be much appreciated!

**Comment by divanvb** [comment]
@muaazrafi Did you manage to render the events inside an iframe for heatmap displaying etc? I'm trying to do the same but haven't managed to get it working yet.

**Comment by c0mpli** [comment]
the code is deleted. does someone have access to it?
