### ISSUE TITLE
_isBlockedElement regex logic error

### ISSUE THREAD

**Issue by AMStrix** [rrweb-io/rrweb-snapshot#68]
`_isBlockedElement` Always returns `false` when `blockClass` is `RegExp`. The return statement in the `forEach` just exits the forEach callback function.

https://github.com/rrweb-io/rrweb-snapshot/blob/2ad7be639b65bdbc2813c4948f89488773678aad/src/snapshot.ts#L186-L190

**Comment by Yuyz0112** [comment]
This should be fixed with:
https://github.com/rrweb-io/rrweb-snapshot/pull/64
