### ISSUE TITLE
Password inputs values are serialized by default

### ISSUE THREAD

**Issue by BenoitZugmeyer** [rrweb-io/rrweb-snapshot#75]
Contrary to the [RRWeb guide](https://github.com/rrweb-io/rrweb/blob/master/guide.md#privacy) documentation, password values are serialized during full snapshots or "mutation" incremental snapshots.

This may be especially critical when snapshots are taken after the page "load" event (ex: automatic checkout, `takeFullSnapshot` API).

A workaround could be to avoid collecting `attributes.value` if the input type is `"password"` [here](https://github.com/rrweb-io/rrweb-snapshot/blob/362359eccc60cac2e35129cf822a0e6fa590c011/src/snapshot.ts#L434-L446).

**Comment by Yuyz0112** [comment]
Thanks! This is really a critical issue, we only mask password input events before and forget the snapshot part.

I had merged https://github.com/rrweb-io/rrweb-snapshot/pull/73 so we can config mask password from options.

And in the latest commit, I set the default value of masking password to true when a user does not pass in any explicit config about it.
